In [2]:
import numpy as np

grid = [[6,7,2,0,0,1,9,8,4],
       [0,3,1,0,0,0,0,0,0],
       [0,4,0,0,2,0,0,0,3],
       [4,0,5,0,0,0,3,0,8],
       [9,2,0,3,7,0,5,0,0],
       [7,6,0,0,0,0,0,2,0],
       [0,0,0,4,9,0,8,3,2],
       [3,0,6,0,0,0,0,4,5],
       [0,0,4,0,5,0,1,9,6]]

# print(np.matrix(grid))

def is_Number_Possible(row, column, number):
    global grid
    
    for i in range(9):
        # check if number is present in the given row
        if grid[row][i] == number:
            return False
        
        # check if number is present in the given colunm
        if grid[i][column] == number:
            return False
    
    # check if number is present in the given square
    new_row = (row // 3) * 3
    new_column = (column // 3) * 3
    for i in range(new_row, new_row+3):
        for j in range(new_column, new_column+3):
            if grid[i][j] == number:
                return False
            
    return True

def Sudoku_Solver():
    global grid
    for row in range(9):
        for column in range(9):
            if grid[row][column] == 0:
                for number in range(1,10):
                    if is_Number_Possible(row, column, number):
                        grid[row][column] = number
                        Sudoku_Solver()
                        grid[row][column] = 0          # Backtracking
                return
    print(np.matrix(grid))
    
    
Sudoku_Solver()

[[6 7 2 5 3 1 9 8 4]
 [8 3 1 6 4 9 2 5 7]
 [5 4 9 8 2 7 6 1 3]
 [4 1 5 9 6 2 3 7 8]
 [9 2 8 3 7 4 5 6 1]
 [7 6 3 1 8 5 4 2 9]
 [1 5 7 4 9 6 8 3 2]
 [3 9 6 2 1 8 7 4 5]
 [2 8 4 7 5 3 1 9 6]]
